services:
  client:
    image: ghcr.io/headary/problem-manager-client:master
    restart: on-failure:3
    environment:
      APP_ROOT_URL: ''
      APP_API_URL: ''
      APP_WS_URL: ''
      APP_OIDC_AUTHORITY_URL: ''
      APP_OIDC_CLIENT_ID: ''
  server:
    image: ghcr.io/headary/problem-manager-server:master
    restart: on-failure:3
    volumes:
      - ./server/config.json:/app/server/config.json
      - ./task_data:/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  db:
    image: postgres:17
    restart: on-failure:3
    shm_size: 128mb
    environment:
      POSTGRES_DB: problem_manager
      POSTGRES_USER: pm # change this
      POSTGRES_PASSWORD: password # change this
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
  builder:
    image: ghcr.io/headary/problem-manager-builder:master
    restart: on-failure:3
    volumes:
      - ./task_data:/data
  adminer:
    image: adminer
    restart: always
