name: Eslint
on: [push, pull_request]
jobs:
  client:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install server dependencies
        working-directory: ./client
        run: npm install
      - name: Install client dependencies
        working-directory: ./client
        run: npm install
      - name: Run client eslint
        working-directory: ./client
        run: npm run lint
