name: Eslint
on: [push, pull_request]

jobs:
  client:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm install
      - name: Install server dependencies
        working-directory: server
        run: npm install
      - name: Install latex
        working-directory: lang-latex
        run: npm install
      - name: Run client eslint
        working-directory: client
        run: npm run lint

  server:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        working-directory: server
        run: npm install
      - name: Install latex
        working-directory: lang-latex
        run: npm install
      - name: Run client eslint
        working-directory: server
        run: npm run lint

  builder:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        working-directory: builder
        run: npm install
      - name: Run client eslint
        working-directory: builder
        run: npm run lint
