name: Prettier
on: [push, pull_request]
jobs:
  client:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Check formatting
        working-directory: ./client
        run: npx prettier . --check --config ../.prettierrc

  server:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
      - name: Install dependencies
        working-directory: ./server
        run: npm install
      - name: Check formatting
        working-directory: ./server
        run: npx prettier . --check --config ../.prettierrc


  builder:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: ./builder/package-lock.json
      - name: Install dependencies
        working-directory: ./builder
        run: npm install
      - name: Check formatting
        working-directory: ./builder
        run: npx prettier . --check --config ../.prettierrc
